import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('ar'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'language.title': 'Choose your language',
      'language.subtitle':
          'We will personalize the experience based on your preference.',
      'language.english': 'English',
      'language.arabic': 'Arabic',
      'language.cta': 'Continue',
      'intro.slide1Title': 'Welcome to FitCoach+',
      'intro.slide1Body':
          'Personalized coaching, workouts, and nutrition guidance in one app.',
      'intro.slide2Title': 'Talk to your coach',
      'intro.slide2Body':
          'Chat, video, and progress tracking stay synced with your trainer.',
      'intro.slide3Title': 'Shop & fuel smarter',
      'intro.slide3Body':
          'Discover curated products and plans that match your journey.',
      'intro.skip': 'Skip',
      'intro.next': 'Next',
      'intro.getStarted': 'Get Started',
      'auth.phonePrimaryCta': 'Continue with phone number',
      'auth.useEmailInstead': 'Use email instead',
      'auth.phoneHelpText':
          'You will receive a secure one-time passcode to sign in.',
      'auth.phoneTitle': 'Verify your phone number',
      'auth.phoneSubtitle':
          'Enter your number and we will text you a secure code.',
      'auth.enterCodeCta': 'Enter the verification code we just sent you.',
      'auth.changeNumber': 'Use a different number',
      'auth.demoHint':
          'Long-press the logo on the intro screen any time to enter demo mode.',
      'auth.demoCta': 'Preview the experience in demo mode',
      'demo.enabled': 'Demo mode enabled',
      'demo.disabled': 'Demo mode disabled',
      'auth.phonePlaceholder': 'Phone (e.g. +1 5551234567)',
      'auth.otpPlaceholder': 'Enter OTP',
      'auth.sendOtp': 'Send OTP',
      'auth.verifyOtp': 'Verify & Continue',
      'auth.resendOtp': 'Resend code',
      'auth.phoneUnavailable': 'Phone auth unavailable',
      'auth.invalidPhone': 'Enter a valid phone number (e.g. +15551234567).',
      'auth.invalidOtp': 'Enter the 6-digit code.',
      'auth.codeSent': 'We just sent a code to your phone.',
      'auth.autoVerificationFailed':
          'Auto verification failed. Please enter the code manually.',
      'auth.sendOtpFirst': 'Send the code first.',
      'common.continue': 'Continue',
      'common.back': 'Back',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'common.retry': 'Retry',
      'workouts.reportInjury': 'Report Injury',
      'workouts.injuryDialog.title': 'Report an Injury',
      'workouts.injuryDialog.description':
          'Select the injured area to replace {exercise}.',
      'workouts.injuryDialog.selectArea': 'Injured Area',
      'workouts.injuryDialog.impactNotice':
          'We will only suggest exercises that are safe for this injury.',
      'workouts.findAlternative': 'Find Alternatives',
      'workouts.alternatives.title': 'Safe Alternatives',
      'workouts.alternatives.description':
          'These exercises are safe for your {injury} injury.',
      'workouts.safeFor': 'Safe for',
      'workouts.useThis': 'Use This',
      'workouts.swapped': 'Swapped',
      'workouts.originalExercise': 'Original',
      'workouts.noAlternatives': 'No safe alternatives available right now.',
      'workouts.swapSuccess': 'Exercise swapped successfully.',
      'workouts.planHeroSubtitle': 'Rolling {weeks}-week schedule tailored to your goal.',
      'workouts.planStartToday': 'Start today\'s session',
      'workouts.planStart': 'Start session',
      'workouts.planViewDetails': 'View details',
      'workouts.planEmptyTitle': 'No workout plan available',
      'workouts.planEmptySubtitle': 'Pull to refresh after your coach assigns a new plan.',
      'workouts.planTutorialTitle': 'Follow your two-week plan',
      'workouts.planTutorialBody': 'Tap any day to preview exercises, swap moves, or jump straight into a session.',
      'workouts.planDismiss': 'Got it',
      'workouts.planCompletedLabel': 'Completed',
      'workouts.planUpcomingLabel': 'Upcoming',
      'workouts.planTodayLabel': 'Today',
      'workouts.planRestLabel': 'Rest',
      'workouts.planWeeksLabel': 'Weeks',
      'workouts.planWeek': 'Week {index}',
      'workouts.planExercisesCount': '{count} exercises',
      'injuries.shoulder': 'Shoulder',
      'injuries.knee': 'Knee',
      'injuries.lower_back': 'Lower Back',
      'injuries.neck': 'Neck',
      'injuries.ankle': 'Ankle',
      'nutrition.todayTitle': "Today's Nutrition",
      'nutrition.mealSummary': 'Meal overview',
      'nutrition.totalAssigned': 'Assigned',
      'nutrition.totalLogged': 'Logged',
      'nutrition.remaining': 'Remaining',
      'nutrition.planFoods': 'Assigned foods',
      'nutrition.noPlanItems': 'No foods assigned for this meal.',
      'nutrition.loggedFoods': 'Your food log',
      'nutrition.emptyLogs': 'No foods logged yet.',
      'nutrition.logFood': 'Log Food',
      'nutrition.viewMeal': 'View meal details',
      'nutrition.addFood': 'Add Food',
      'nutrition.editEntry': 'Edit Entry',
      'nutrition.deleteEntry': 'Delete Entry',
      'nutrition.deleteEntryConfirm': 'Remove this food log?',
      'nutrition.searchFood': 'Search',
      'nutrition.customFood': 'Custom',
      'nutrition.searchPlaceholder': 'Search foods…',
      'nutrition.foodName': 'Food name',
      'nutrition.servingSize': 'Serving size',
      'nutrition.calories': 'Calories',
      'nutrition.protein': 'Protein',
      'nutrition.carbs': 'Carbs',
      'nutrition.fats': 'Fats',
      'nutrition.notes': 'Notes',
      'nutrition.addToMeal': 'Add to meal',
      'nutrition.validationFoodRequired': 'Enter a food name and calories.',
      'nutrition.loggedAt': 'Logged at {time}',
      'nutrition.foodLogged': 'Food logged.',
      'nutrition.foodUpdated': 'Entry updated.',
      'nutrition.foodDeleted': 'Entry removed.',
    'nutrition.unlocked': 'Unlimited nutrition access',
    'nutrition.windowDays': '{days}-day window',
      'coach.clientDetails': 'Client Details',
      'coach.message': 'Message',
      'coach.call': 'Call',
      'coach.assignPlan': 'Assign Plan',
      'coach.overview': 'Overview',
      'coach.sessions': 'Sessions',
      'coach.nutrition': 'Nutrition',
      'coach.quickActions': 'Quick actions',
      'coach.subscription': 'Subscription',
      'coach.goal': 'Primary goal',
      'coach.lastActive': 'Last active {date}',
      'coach.noData': 'No data available yet.',
      'coach.recentSessions': 'Recent sessions',
      'coach.milestones': 'Milestones',
      'coach.nutritionLogs': 'Nutrition logs',
      'coach.viewClient': 'View client',
      'coach.progress': 'Progress',
      'coach.fitnessScore': 'Fitness score',
      'coach.contactClient': 'Contact client',
      'coach.assignComingSoon': 'Program assignment coming soon.',
      'coach.messageComingSoon': 'Messaging coming soon.',
      'coach.callComingSoon': 'Calling coming soon.',
      'coach.messagesTitle': 'Messages',
      'coach.messagesEmpty': 'No messages yet.',
      'coach.filterAllClients': 'All clients',
      'coach.attachmentLocked':
          'Attachments are only available for Smart Premium.',
      'coach.attachmentHint': 'Paste a secure URL (JPEG/PNG/PDF up to 10MB).',
      'coach.messagePlaceholder': 'Type your message…',
      'coach.sendMessage': 'Send message',
      'coach.openMessaging': 'Open messaging',
      'coach.quotaWarning': 'You have used {percent}% of your quota.',
      'coach.selectClientFirst': 'Select a client before sending.',
      'coach.myProfile': 'My Profile',
      'coach.professionalProfile': 'Professional coaching profile',
      'coach.verified': 'Verified Coach',
      'coach.reviews': 'reviews',
      'coach.yearsExp': 'years experience',
      'coach.totalClients': 'Total Clients',
      'coach.activeClients': 'Active Clients',
      'coach.successRate': 'Success Rate',
      'coach.monthlyRevenue': 'Monthly Revenue',
      'coach.myCertificates': 'My Certificates',
      'coach.addCertificate': 'Add Certificate',
      'coach.issued': 'Issued',
      'coach.expires': 'Expires',
      'coach.viewCertificate': 'View Certificate',
      'coach.workExperience': 'Work Experience',
      'coach.addExperience': 'Add Experience',
      'coach.current': 'Current',
      'coach.present': 'Present',
      'coach.myAchievements': 'My Achievements',
      'coach.addAchievement': 'Add Achievement',
      'coach.certificates': 'Certificates',
      'coach.experience': 'Experience',
      'coach.achievements': 'Achievements',
      'coach.contactInfo': 'Contact Information',
      'coach.specializations': 'Specializations',
      'coach.bio': 'Professional Bio',
      'coach.viewProfile': 'View Profile',
      'coach.bookVideo': 'Book Video Session',
      'coach.messageCoach': 'Message Coach',
      'account.profileUpdated': 'Profile updated successfully',
      'account.bioUpdated': 'Bio updated successfully',
      'account.email': 'Email',
      'account.phone': 'Phone',
    // Nutrition preferences intake
    'nutritionPrefs.title': 'Nutrition Preferences',
    'nutritionPrefs.step': 'Step',
    'nutritionPrefs.protein.title': 'Protein Preferences',
    'nutritionPrefs.protein.subtitle': 'Which protein sources do you prefer? Select all that apply.',
    'nutritionPrefs.allergies.title': 'Allergies & Intolerances',
    'nutritionPrefs.allergies.subtitle': 'Mark any proteins you cannot eat.',
    'nutritionPrefs.dinner.title': 'Dinner Style',
    'nutritionPrefs.dinner.subtitle': 'How do you prefer your dinner?',
    'nutritionPrefs.portionSize': 'Portion Size',
    'nutritionPrefs.portionSize.light': 'Light',
    'nutritionPrefs.portionSize.moderate': 'Moderate',
    'nutritionPrefs.portionSize.filling': 'Filling',
    'nutritionPrefs.prepTime': 'Prep Time',
    'nutritionPrefs.prepTime.quick': 'Quick (<15 min)',
    'nutritionPrefs.prepTime.normal': 'Normal (15-25 min)',
    'nutritionPrefs.prepTime.prepAhead': 'Prep-ahead',
    'nutritionPrefs.carbs': 'Carbohydrates',
    'nutritionPrefs.carbs.noCarb': 'No-carb',
    'nutritionPrefs.carbs.lowCarb': 'Low-carb',
    'nutritionPrefs.carbs.includesCarbs': 'Includes carbs',
    'nutritionPrefs.cuisines': 'Favorite Cuisines',
    'nutritionPrefs.cuisines.subtitle': 'Select at least one cuisine you enjoy',
    'nutritionPrefs.avoid.title': 'Foods to Avoid',
    'nutritionPrefs.avoid.subtitle': 'Select foods you want us to avoid',
    'nutritionPrefs.temperature': 'Serving Temperature',
    'nutritionPrefs.temperature.hot': 'Hot',
    'nutritionPrefs.temperature.cold': 'Cold',
    'nutritionPrefs.temperature.both': 'Both',
    'nutritionPrefs.notes.title': 'Additional Notes',
    'nutritionPrefs.notes.subtitle': 'Anything else we should know?',
    'nutritionPrefs.notes.placeholder': 'e.g., prefer less salt, vegetarian weekdays…',
    'nutritionPrefs.complete': 'You\'re all set!',
    'nutritionPrefs.completeDesc': 'We will generate personalized plans using these preferences.',
    'nutritionPrefs.completeSetup': 'Complete Setup',
    'nutritionPrefs.previous': 'Previous',
    'foods.chicken': 'Chicken',
    'foods.beef': 'Red meat',
    'foods.tuna': 'Tuna',
    'foods.shrimp': 'Shrimp',
    'foods.salmon': 'Salmon',
    'foods.eggs': 'Eggs',
    'foods.beans': 'Beans & legumes',
    'foods.tofu': 'Tofu',
    'foods.spicy': 'Spicy foods',
    'foods.fried': 'Fried foods',
    'foods.dairy': 'Dairy',
    'foods.gluten': 'Gluten',
    'foods.seafood': 'Seafood',
    'foods.nuts': 'Nuts',
    'foods.shellfish': 'Shellfish',
    'cuisines.egyptian': 'Egyptian',
    'cuisines.middle_eastern': 'Middle Eastern',
    'cuisines.mediterranean': 'Mediterranean',
    'cuisines.asian': 'Asian',
    'cuisines.american': 'Western',
    'cuisines.indian': 'Indian',
    // Quota labels
    'quota.messages': 'Messages',
    'quota.calls': 'Video Calls',
    'quota.attachments': 'Attachments',
    'quota.remaining': 'remaining',
    'quota.unlimited': 'Unlimited',
    'quota.exceeded': 'Quota exceeded',
    'quota.upgradePrompt': 'Upgrade to continue',
    'quota.runningLow': 'Running low',
    'quota.monthlyUsage': 'Monthly Usage',
    'quota.resetsOn': 'Resets on {date}',
    'quota.upgradeForMore': 'Upgrade for more quota',
            // Subscription Manager
            'subscription.title': 'Subscription Plans',
            'subscription.compare': 'Compare Plans',
            'subscription.current': 'Your Current Plan',
            'subscription.workouts': 'Workouts',
            'subscription.nutrition': 'Nutrition',
            'subscription.store': 'Store',
            'subscription.features': 'Features',
            'subscription.freemium': 'Freemium',
            'subscription.premium': 'Premium',
            'subscription.smartPremium': 'Smart Premium',
            'subscription.mostPopular': 'Most Popular',
            'subscription.bestValue': 'Best Value',
            'subscription.currentPlan': 'Current Plan',
            'subscription.selectPlan': 'Select Plan',
            'subscription.upgradeButton': 'Upgrade to',
            'subscription.upgrading': 'Upgrading...',
            'subscription.upgradeSuccess': 'Plan upgraded successfully!',
            'subscription.perMonth': 'per month',
            'subscription.unlimited': 'Unlimited',
            'subscription.included': 'Included',
            'subscription.notIncluded': 'Not Included',
            'subscription.workoutPlans': 'Workout Plans',
            'subscription.weekCycle': 'week cycle',
            'subscription.adaptiveAI': 'Adaptive AI plans',
            'subscription.basicPreferences': 'Basic preferences',
            'subscription.mealPersonalization': 'Meal Personalization',
            'subscription.aiPowered': 'AI-powered suggestions',
            'subscription.coachMessages': 'Coach Messages',
            'subscription.videoSessions': 'Video Sessions',
            'subscription.storeDiscounts': 'Store Discounts',
            'subscription.off': 'off',
            'subscription.advancedAnalytics': 'Advanced Analytics',
            'subscription.basicReports': 'Basic reports',
            'subscription.detailedInsights': 'Detailed insights',
    },
    'ar': {
      'language.title': 'اختر لغتك',
      'language.subtitle': 'سنضبط التطبيق بناءً على تفضيلك.',
      'language.english': 'الإنجليزية',
      'language.arabic': 'العربية',
      'language.cta': 'متابعة',
      'intro.slide1Title': 'مرحباً بك في FitCoach+',
      'intro.slide1Body': 'تدريب مخصص وتمارين وتغذية في تطبيق واحد.',
      'intro.slide2Title': 'تواصل مع مدربك',
      'intro.slide2Body': 'الدردشة والفيديو وتتبع التقدم في مكان واحد.',
      'intro.slide3Title': 'تسوق وتغذى بذكاء',
      'intro.slide3Body': 'اكتشف منتجات وخططاً تناسب رحلتك.',
      'intro.skip': 'تخطي',
      'intro.next': 'التالي',
      'intro.getStarted': 'ابدأ الآن',
      'auth.phonePrimaryCta': 'المتابعة برقم الهاتف',
      'auth.useEmailInstead': 'استخدم البريد الإلكتروني',
      'auth.phoneHelpText': 'سنعيد إرسال رمز تحقق آمن لتسجيل الدخول.',
      'auth.phoneTitle': 'تأكيد رقم هاتفك',
      'auth.phoneSubtitle': 'أدخل رقمك وسنرسل لك رمز تحقق آمن.',
      'auth.enterCodeCta': 'أدخل رمز التحقق الذي أرسلناه لك الآن.',
      'auth.changeNumber': 'استخدام رقم مختلف',
      'auth.demoHint':
          'اضغط مطولاً على الشعار في شاشة المقدمة للدخول إلى وضع العرض.',
      'auth.demoCta': 'استكشف التطبيق في وضع العرض',
      'demo.enabled': 'تم تفعيل وضع العرض',
      'demo.disabled': 'تم إيقاف وضع العرض',
      'auth.phonePlaceholder': 'رقم الهاتف (مثال +9665...)',
      'auth.otpPlaceholder': 'أدخل رمز التحقق',
      'auth.sendOtp': 'إرسال الرمز',
      'auth.verifyOtp': 'تحقق واستمر',
      'auth.resendOtp': 'إعادة إرسال الرمز',
      'auth.phoneUnavailable': 'خدمة التحقق عبر الهاتف غير متاحة',
      'auth.invalidPhone': 'أدخل رقم هاتف صحيح (مثال +9665...).',
      'auth.invalidOtp': 'أدخل رمزاً مكوناً من 6 أرقام.',
      'auth.codeSent': 'لقد أرسلنا الرمز إلى هاتفك الآن.',
      'auth.autoVerificationFailed':
          'فشل التحقق التلقائي، يرجى إدخال الرمز يدوياً.',
      'auth.sendOtpFirst': 'أرسل الرمز أولاً.',
      'common.continue': 'متابعة',
      'common.back': 'رجوع',
      'common.cancel': 'إلغاء',
      'common.save': 'حفظ',
      'common.retry': 'إعادة المحاولة',
      'workouts.reportInjury': 'الإبلاغ عن إصابة',
      'workouts.injuryDialog.title': 'الإبلاغ عن إصابة',
      'workouts.injuryDialog.description':
          'اختر منطقة الإصابة لاستبدال {exercise}.',
      'workouts.injuryDialog.selectArea': 'منطقة الإصابة',
      'workouts.injuryDialog.impactNotice': 'سنقترح تمارين آمنة لهذه الإصابة.',
      'workouts.findAlternative': 'ابحث عن بدائل',
      'workouts.alternatives.title': 'تمارين بديلة آمنة',
      'workouts.alternatives.description': 'هذه التمارين آمنة لإصابة {injury}.',
      'workouts.safeFor': 'آمن لـ',
      'workouts.useThis': 'استخدم هذا',
      'workouts.swapped': 'تم الاستبدال',
      'workouts.originalExercise': 'التمرين الأصلي',
      'workouts.noAlternatives': 'لا توجد بدائل آمنة حالياً.',
      'workouts.swapSuccess': 'تم استبدال التمرين بنجاح.',
      'workouts.planHeroSubtitle': 'جدول متجدد لمدة {weeks} أسابيع حسب هدفك.',
      'workouts.planStartToday': 'ابدأ حصة اليوم',
      'workouts.planStart': 'ابدأ الحصة',
      'workouts.planViewDetails': 'عرض التفاصيل',
      'workouts.planEmptyTitle': 'لا توجد خطة تمارين متاحة',
      'workouts.planEmptySubtitle': 'اسحب للتحديث بعد أن يعيّن المدرب خطة جديدة.',
      'workouts.planTutorialTitle': 'اتبع خطة الأسبوعين',
      'workouts.planTutorialBody': 'اضغط على أي يوم لعرض التمارين أو تبديل الحركات أو البدء فوراً.',
      'workouts.planDismiss': 'حسناً',
      'workouts.planCompletedLabel': 'مكتمل',
      'workouts.planUpcomingLabel': 'قادمة',
      'workouts.planTodayLabel': 'اليوم',
      'workouts.planRestLabel': 'راحة',
      'workouts.planWeeksLabel': 'أسابيع',
      'workouts.planWeek': 'الأسبوع {index}',
      'workouts.planExercisesCount': '{count} تمارين',
      'injuries.shoulder': 'الكتف',
      'injuries.knee': 'الركبة',
      'injuries.lower_back': 'أسفل الظهر',
      'injuries.neck': 'الرقبة',
      'injuries.ankle': 'الكاحل',
      'nutrition.todayTitle': 'تغذية اليوم',
      'nutrition.mealSummary': 'ملخص الوجبة',
      'nutrition.totalAssigned': 'مقرر',
      'nutrition.totalLogged': 'مُسجل',
      'nutrition.remaining': 'المتبقي',
      'nutrition.planFoods': 'أطعمة الخطة',
      'nutrition.noPlanItems': 'لا توجد أطعمة محددة لهذه الوجبة.',
      'nutrition.loggedFoods': 'سجل طعامك',
      'nutrition.emptyLogs': 'لم يتم تسجيل أطعمة بعد.',
      'nutrition.logFood': 'سجل طعامًا',
      'nutrition.viewMeal': 'عرض تفاصيل الوجبة',
      'nutrition.addFood': 'إضافة طعام',
      'nutrition.editEntry': 'تعديل السجل',
      'nutrition.deleteEntry': 'حذف السجل',
      'nutrition.deleteEntryConfirm': 'هل تريد حذف هذا السجل؟',
      'nutrition.searchFood': 'بحث',
      'nutrition.customFood': 'مخصص',
      'nutrition.searchPlaceholder': 'ابحث عن الأطعمة…',
      'nutrition.foodName': 'اسم الطعام',
      'nutrition.servingSize': 'حجم الحصة',
      'nutrition.calories': 'سعرات حرارية',
      'nutrition.protein': 'بروتين',
      'nutrition.carbs': 'كربوهيدرات',
      'nutrition.fats': 'دهون',
      'nutrition.notes': 'ملاحظات',
      'nutrition.addToMeal': 'أضف إلى الوجبة',
      'nutrition.validationFoodRequired': 'أدخل اسم الطعام والسعرات الحرارية.',
      'nutrition.loggedAt': 'تم التسجيل في {time}',
      'nutrition.foodLogged': 'تم تسجيل الطعام.',
      'nutrition.foodUpdated': 'تم تحديث السجل.',
      'nutrition.foodDeleted': 'تم حذف السجل.',
      'nutrition.unlocked': 'وصول تغذية غير محدود',
      'nutrition.windowDays': 'نافذة تغذية لمدة {days} يومًا',
      'coach.clientDetails': 'تفاصيل العميل',
      'coach.message': 'رسالة',
      'coach.call': 'اتصال',
      'coach.assignPlan': 'تعيين خطة',
      'coach.overview': 'نظرة عامة',
      'coach.sessions': 'الجلسات',
      'coach.nutrition': 'التغذية',
      'coach.quickActions': 'إجراءات سريعة',
      'coach.subscription': 'الاشتراك',
      'coach.goal': 'الهدف الأساسي',
      'coach.lastActive': 'آخر نشاط {date}',
      'coach.noData': 'لا توجد بيانات بعد.',
      'coach.recentSessions': 'أحدث الجلسات',
      'coach.milestones': 'الإنجازات',
      'coach.nutritionLogs': 'سجلات التغذية',
      'coach.viewClient': 'عرض العميل',
      'coach.progress': 'التقدم',
      'coach.fitnessScore': 'درجة اللياقة',
      'coach.contactClient': 'تواصل مع العميل',
      'coach.assignComingSoon': 'ميزة تعيين البرامج قريباً.',
      'coach.messageComingSoon': 'ميزة المراسلة قريباً.',
      'coach.callComingSoon': 'ميزة الاتصال قريباً.',
      'coach.messagesTitle': 'الرسائل',
      'coach.messagesEmpty': 'لا توجد رسائل بعد.',
      'coach.filterAllClients': 'كل العملاء',
      'coach.attachmentLocked': 'المرفقات متاحة لمشتركي سمارت بريميوم فقط.',
      'coach.attachmentHint':
          'ألصق رابطاً آمناً (JPEG/PNG/PDF حتى 10 ميغابايت).',
      'coach.messagePlaceholder': 'اكتب رسالتك…',
      'coach.sendMessage': 'إرسال الرسالة',
      'coach.openMessaging': 'فتح المراسلة',
      'coach.quotaWarning': 'لقد استخدمت {percent}% من حصتك.',
      'coach.selectClientFirst': 'اختر عميلاً قبل الإرسال.',
      'coach.myProfile': 'ملفي الشخصي',
      'coach.professionalProfile': 'الملف التدريبي المهني',
      'coach.verified': 'مدرب معتمد',
      'coach.reviews': 'تقييمات',
      'coach.yearsExp': 'سنوات خبرة',
      'coach.totalClients': 'إجمالي العملاء',
      'coach.activeClients': 'العملاء النشطون',
      'coach.successRate': 'معدل النجاح',
      'coach.monthlyRevenue': 'الإيرادات الشهرية',
      'coach.myCertificates': 'شهاداتي',
      'coach.addCertificate': 'إضافة شهادة',
      'coach.issued': 'صادرة في',
      'coach.expires': 'تنتهي في',
      'coach.viewCertificate': 'عرض الشهادة',
      'coach.workExperience': 'الخبرة العملية',
      'coach.addExperience': 'إضافة خبرة',
      'coach.current': 'حالي',
      'coach.present': 'الآن',
      'coach.myAchievements': 'إنجازاتي',
      'coach.addAchievement': 'إضافة إنجاز',
      'coach.certificates': 'الشهادات',
      'coach.experience': 'الخبرة',
      'coach.achievements': 'الإنجازات',
      'coach.contactInfo': 'معلومات الاتصال',
      'coach.specializations': 'التخصصات',
      'coach.bio': 'السيرة المهنية',
      'coach.viewProfile': 'عرض الملف',
      'coach.bookVideo': 'حجز جلسة فيديو',
      'coach.messageCoach': 'مراسلة المدرب',
      'account.profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
      'account.bioUpdated': 'تم تحديث السيرة بنجاح',
      'account.email': 'البريد الإلكتروني',
      'account.phone': 'رقم الهاتف',
      // Nutrition preferences intake
      'nutritionPrefs.title': 'تفضيلات التغذية',
      'nutritionPrefs.step': 'الخطوة',
      'nutritionPrefs.protein.title': 'تفضيلات البروتين',
      'nutritionPrefs.protein.subtitle': 'ما هي مصادر البروتين التي تفضلها؟ اختر كل ما ينطبق.',
      'nutritionPrefs.allergies.title': 'الحساسية والقيود',
      'nutritionPrefs.allergies.subtitle': 'حدد أي بروتينات لا يمكنك تناولها.',
      'nutritionPrefs.dinner.title': 'نمط العشاء',
      'nutritionPrefs.dinner.subtitle': 'كيف تفضل عشاءك عادة؟',
      'nutritionPrefs.portionSize': 'حجم الحصة',
      'nutritionPrefs.portionSize.light': 'خفيف',
      'nutritionPrefs.portionSize.moderate': 'متوسط',
      'nutritionPrefs.portionSize.filling': 'مشبع',
      'nutritionPrefs.prepTime': 'وقت التحضير',
      'nutritionPrefs.prepTime.quick': 'سريع (أقل من 15 دقيقة)',
      'nutritionPrefs.prepTime.normal': 'عادي (15-25 دقيقة)',
      'nutritionPrefs.prepTime.prepAhead': 'تحضير مسبق',
      'nutritionPrefs.carbs': 'الكربوهيدرات',
      'nutritionPrefs.carbs.noCarb': 'بدون كربوهيدرات',
      'nutritionPrefs.carbs.lowCarb': 'قليل الكربوهيدرات',
      'nutritionPrefs.carbs.includesCarbs': 'يتضمن كربوهيدرات',
      'nutritionPrefs.cuisines': 'المأكولات المفضلة',
      'nutritionPrefs.cuisines.subtitle': 'اختر مأكولاتك المفضلة (واحدة على الأقل)',
      'nutritionPrefs.avoid.title': 'أطعمة يجب تجنبها',
      'nutritionPrefs.avoid.subtitle': 'اختر الأطعمة التي تفضل تجنبها',
    'nutritionPrefs.temperature': 'درجة تقديم الطعام',
    'nutritionPrefs.temperature.hot': 'ساخن',
    'nutritionPrefs.temperature.cold': 'بارد',
    'nutritionPrefs.temperature.both': 'كلاهما',
      'nutritionPrefs.notes.title': 'ملاحظات إضافية',
      'nutritionPrefs.notes.subtitle': 'أي متطلبات غذائية أخرى؟',
      'nutritionPrefs.notes.placeholder': 'مثال: أفضل ملح أقل، نباتي في أيام الأسبوع…',
      'nutritionPrefs.complete': 'اكتمل الإعداد!',
      'nutritionPrefs.completeDesc': 'سننشئ خطط تغذية شخصية بناءً على هذه التفضيلات.',
      'nutritionPrefs.completeSetup': 'إكمال الإعداد',
      'nutritionPrefs.previous': 'السابق',
    'foods.chicken': 'دجاج',
    'foods.beef': 'لحوم حمراء',
    'foods.tuna': 'تونا',
    'foods.shrimp': 'روبيان',
    'foods.salmon': 'سلمون',
    'foods.eggs': 'بيض',
    'foods.beans': 'فاصوليا وبقوليات',
    'foods.tofu': 'توفو',
    'foods.spicy': 'أطعمة حارة',
    'foods.fried': 'أطعمة مقلية',
    'foods.dairy': 'ألبان',
    'foods.gluten': 'غلوتين',
    'foods.seafood': 'مأكولات بحرية',
    'foods.nuts': 'مكسرات',
    'foods.shellfish': 'قشريات',
    'cuisines.egyptian': 'مصري',
    'cuisines.middle_eastern': 'شرق أوسطي',
    'cuisines.mediterranean': 'متوسطي',
    'cuisines.asian': 'آسيوي',
    'cuisines.american': 'غربي',
    'cuisines.indian': 'هندي',
      // Quota labels
      'quota.messages': 'الرسائل',
      'quota.calls': 'مكالمات الفيديو',
      'quota.attachments': 'المرفقات',
      'quota.remaining': 'متبقي',
      'quota.unlimited': 'غير محدود',
      'quota.exceeded': 'تم تجاوز الحصة',
      'quota.upgradePrompt': 'قم بالترقية للمتابعة',
      'quota.runningLow': 'الحصة على وشك النفاد',
      'quota.monthlyUsage': 'الاستخدام الشهري',
      'quota.resetsOn': 'يعاد التعيين في {date}',
      'quota.upgradeForMore': 'قم بالترقية للمزيد',
            // Subscription Manager
            'subscription.title': 'خطط الاشتراك',
            'subscription.compare': 'مقارنة الخطط',
            'subscription.current': 'خطتك الحالية',
            'subscription.workouts': 'التمارين',
            'subscription.nutrition': 'التغذية',
            'subscription.store': 'المتجر',
            'subscription.features': 'المميزات',
            'subscription.freemium': 'مجاني',
            'subscription.premium': 'بريميوم',
            'subscription.smartPremium': 'بريميوم ذكي',
            'subscription.mostPopular': 'الأكثر شيوعاً',
            'subscription.bestValue': 'أفضل قيمة',
            'subscription.currentPlan': 'الخطة الحالية',
            'subscription.selectPlan': 'اختر الخطة',
            'subscription.upgradeButton': 'ترقية إلى',
            'subscription.upgrading': 'جاري الترقية...',
            'subscription.upgradeSuccess': 'تمت ترقية خطتك بنجاح!',
            'subscription.perMonth': 'شهرياً',
            'subscription.unlimited': 'غير محدود',
            'subscription.included': 'مشمول',
            'subscription.notIncluded': 'غير مشمول',
            'subscription.workoutPlans': 'خطط التمارين',
            'subscription.weekCycle': 'دورة أسبوعية',
            'subscription.adaptiveAI': 'خطط ذكية متكيفة',
            'subscription.basicPreferences': 'تفضيلات أساسية',
            'subscription.mealPersonalization': 'تخصيص الوجبات',
            'subscription.aiPowered': 'اقتراحات مدعومة بالذكاء الاصطناعي',
            'subscription.coachMessages': 'رسائل المدرب',
            'subscription.videoSessions': 'جلسات الفيديو',
            'subscription.storeDiscounts': 'خصومات المتجر',
            'subscription.off': 'خصم',
            'subscription.advancedAnalytics': 'تحليلات متقدمة',
            'subscription.basicReports': 'تقارير أساسية',
            'subscription.detailedInsights': 'رؤى مفصلة',
    },
  };

  String t(String key) {
    final lang = locale.languageCode;
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .any((e) => e.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension LocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
