import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('ar');
  bool _hasSelectedLanguage = false;
  String _currentLanguage = 'ar';

  LanguageProvider() {
    _loadLanguage();
  }

  Locale get locale => _locale;
  bool get hasSelectedLanguage => _hasSelectedLanguage;
  bool get isArabic => _locale.languageCode == 'ar';
  bool get isEnglish => _locale.languageCode == 'en';
  String get currentLanguage => _currentLanguage;

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('fitcoach_language');

    if (languageCode != null) {
      _locale = Locale(languageCode);
      _hasSelectedLanguage = true;
      _currentLanguage = languageCode;
      notifyListeners();
    }
  }

  Future<void> setLanguage(String languageCode) async {
    _locale = Locale(languageCode);
    _hasSelectedLanguage = true;
    _currentLanguage = languageCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('fitcoach_language', languageCode);
    notifyListeners();
  }

  Future<void> toggleLanguage() async {
    if (_locale.languageCode == 'ar') {
      await setLanguage('en');
    } else {
      await setLanguage('ar');
    }
  }

  String translate(String key, {Map<String, String>? args}) {
    String text;
    if (isArabic) {
      text = _arabicTranslations[key] ?? _englishTranslations[key] ?? key;
    } else {
      text = _englishTranslations[key] ?? key;
    }

    if (args != null) {
      args.forEach((key, value) {
        text = text.replaceAll('{$key}', value);
      });
    }

    return text;
  }

  String t(String key, {Map<String, String>? args}) => translate(key, args: args);

  Map<String, String> _getTranslations() {
    if (isArabic) {
      return _arabicTranslations;
    }
    return _englishTranslations;
  }

static const Map<String, String> _englishTranslations = {
    'app_name': 'FitCoach+',
    'welcome': 'Welcome to FitCoach+',
    'select_language': 'Select your language',
    'english': 'English',
    'arabic': 'Arabic',
    'continue': 'Continue',
    'skip': 'Skip',
    'next': 'Next',
    'back': 'Back',
    'save': 'Save',
    'cancel': 'Cancel',
    'loading': 'Loading...',
    'error': 'An error occurred',
    'splash_headline_en': 'Your Fitness Journey Starts Now',
    'splash_headline_ar': 'رحلتك الرياضية تبدأ الآن',
    'splash_start': 'Start / ابدأ',
    
    // Auth
    'auth_app_name': 'FitCoach',
    'auth_tagline': 'Your Fitness Journey Starts Here',
    'auth_welcome': 'Welcome',
    'auth_welcome_subtitle': 'Sign in to continue',
    'auth_continue_with_email': 'Continue with Email',
    'auth_continue_with_phone': 'Continue with Phone',
    'auth_email_or_phone': 'Email or Phone',
    'auth_email_or_phone_placeholder': 'name@example.com or +966...',
    'auth_or_divider': 'OR',
    'auth_phone_will_receive_otp': 'We will send a verification code to this number',
    'auth_enter_otp': 'Enter verification code',
    'auth_otp_sent': 'We sent a code to',
    'auth_sign_in': 'Sign In',
    'auth_sign_up': 'Sign Up',
    'auth_back': 'Back',
    'auth_no_account': 'Don\'t have an account?',
    'auth_have_account': 'Already have an account?',
    'auth_create_account': 'Create Account',
    'auth_create_account_subtitle': 'Join FitCoach and start your journey',
    'auth_full_name': 'Full Name',
    'auth_email': 'Email',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': 'Password',
    'auth_password_placeholder': 'Enter your password',
    'auth_forgot_password': 'Forgot Password?',
    'auth_forgot_password_title': 'Forgot Password',
    'auth_forgot_password_desc': 'Enter your email or phone and we will send a reset link',
    'auth_reset_link_sent': 'Reset link sent',
    'auth_send': 'Send',
    'auth_cancel': 'Cancel',
    'auth_confirm_password': 'Confirm Password',
    'auth_confirm_password_placeholder': 'Re-enter your password',
    'auth_missing_fields': 'Please fill in all required fields',
    'auth_password_mismatch': 'Passwords do not match',
    'auth_try_demo': 'Try Demo',
    'auth_demo_unavailable': 'Demo mode is only available when built with DEMO_MODE',
    'auth_demo_credentials': 'Demo credentials',
    'auth_demo_user': 'Demo User',
    'auth_demo_coach': 'Demo Coach',
    'auth_demo_admin': 'Demo Admin',
    'auth_phone': 'Phone Number',
    'auth_phone_placeholder': '+966 5X XXX XXXX',
    'auth_verify': 'Verify',
    'auth_resend': 'Resend code',
    'auth_resend_in': 'Resend in',
    'auth_attempts_remaining': 'attempts remaining',
    'auth_change_phone': 'Change phone number',
    'enter_phone': 'Enter your phone number',
    'phone_hint': '+966 5X XXX XXXX',
    'send_otp': 'Send OTP',
    'enter_otp': 'Enter verification code',
    'verify': 'Verify',
    'resend': 'Resend code',
    
    // Intake
    'lets_know_you': 'Let\'s get to know you',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'goal': 'What\'s your main goal?',
    'fat_loss': 'Fat Loss',
    'muscle_gain': 'Muscle Gain',
    'general_fitness': 'General Fitness',
    'location': 'Where do you work out?',
    'home': 'Home',
    'home_location': 'Home',
    'gym': 'Gym',
    'age': 'Age',
    'years': 'years',
    'weight': 'Weight',
    'height': 'Height',
    'kg': 'kg',
    'cm': 'cm',
    'complete': 'Complete',
    'intake_incomplete': 'Please complete all required fields',
    'intake_select_option': 'Please select an option',
    'experience_level_title': 'What\'s your experience level?',
    'experience_level_desc': 'This helps tailor your training plan',
    'experience_beginner': 'Beginner',
    'experience_beginner_desc': '0-6 months',
    'experience_intermediate': 'Intermediate',
    'experience_intermediate_desc': '6-24 months',
    'experience_advanced': 'Advanced',
    'experience_advanced_desc': '2+ years',
    'intake_second_age_title': 'What\'s your age?',
    'intake_second_age_desc': 'We use this to personalize your plan',
    'intake_second_body_metrics_title': 'Body metrics',
    'intake_second_body_metrics_desc': 'Enter your current weight and height',
    'intake_second_frequency_title': 'Workout frequency',
    'intake_second_frequency_desc': 'How many days per week can you train?',
    'intake_second_injuries_title': 'Do you have any injuries?',
    'intake_second_injuries_desc': 'We\'ll adjust your plan to stay safe',
    'intake_second_injuries_none': 'No injuries? Great! Just continue',
    'injury_shoulder': 'Shoulder',
    'injury_knee': 'Knee',
    'injury_lower_back': 'Lower Back',
    'injury_neck': 'Neck',
    'injury_ankle': 'Ankle',
    'intake_prompt_title': 'Complete your workout intake',
    'intake_prompt_description': 'Finish a short questionnaire to unlock a personalized plan or book a free call with your coach.',
    'intake_prompt_option1_title': 'Customized workout plan',
    'intake_prompt_option1_desc': 'Answer a few questions to tailor your training.',
    'intake_prompt_option2_title': 'Free coach video call',
    'intake_prompt_option2_desc': 'Get guidance and accountability from a coach.',
    'intake_prompt_free_call': 'Free for you',
    'intake_prompt_book_call': 'Book call',
    'intake_prompt_complete': 'Complete intake',
    'intake_prompt_later': 'Later',
    'intake_generating_title': 'Generating your plan',
    'intake_generating_desc': 'We\'re building your specialized workout plan now.',
    
    // Home
    'workout': 'Workout',
    'nutrition': 'Nutrition',
    'coach': 'Coach',
    'store': 'Store',
    'account': 'Account',
    'greeting': 'Hello, {name}',
    'todays_workout': 'Today\'s Workout',
    'nutrition_plan': 'Nutrition Plan',
    'message_coach': 'Message Coach',
    'no_active_workout_plan': 'No active workout plan',
    'workout_plan_coming_soon': 'Your coach will create a plan for you soon',
    'workout_select_day': 'Select a day to view exercises',
    'workout_overview': 'Workout Overview',
    'workout_day': 'Day {number}',
    'workout_progress': '{completed} of {total} exercises completed',
    'exercises': 'Exercises',
    'completed': 'Completed',
    'sets': 'sets',
    'reps': 'reps',
    'substitute': 'Substitute',
    'substitute_exercise': 'Substitute Exercise',
    'no_alternatives_available': 'No alternatives available',
    'exercise_substituted_successfully': 'Exercise substituted successfully',
    'workout_injury_conflict': 'This exercise may conflict with your injury',
    'home_hello': 'Hello',
    'home_ready': 'Ready for your next session?',
    'home_fitness_score': 'Fitness Score',
    'home_updated_by_coach': 'Updated by coach',
    'home_auto_updated': 'Auto updated',
    'home_calories_burned': 'Calories Burned',
    'home_calories_consumed': 'Calories Consumed',
    'home_workouts_completed': 'Workouts Completed',
    'home_quick_access': 'Quick Access',
    'home_workouts': 'Workouts',
    'home_workouts_desc': 'Training plans and today\'s session',
    'home_nutrition': 'Nutrition',
    'home_nutrition_desc': 'Meals, macros, and daily targets',
    'home_coach': 'Coach',
    'home_coach_desc': 'Chat and video sessions',
    'home_store': 'Store',
    'home_store_desc': 'Supplements and gear',
    'home_locked': 'Locked',
    
    // Workout
    'no_plan': 'No workout plan yet',
    'ask_coach': 'Ask your coach for a plan',
    'start_workout': 'Start Workout',
    'complete_set': 'Complete Set',
    
    // Nutrition
    'trial_period': 'Trial Period',
    'trial_expiring': 'You have {days} days of free access remaining',
    'trial_expired': 'Trial Period Ended',
    'upgrade_to_premium': 'Upgrade to Premium',
    'upgrade_prompt': 'Upgrade to Premium for unlimited access to nutrition plans',
    'macros': 'Macros',
    'protein': 'Protein',
    'carbs': 'Carbs',
    'fats': 'Fats',
    'calories': 'Calories',
    'consumed': 'Consumed',
    'remaining': 'Remaining',
    'cal_unit': 'cal',
    'more_items': '+ {count} more',
    'todays_meals': 'Today\'s Meals',
    'no_active_nutrition_plan': 'No active nutrition plan',
    'nutrition_plan_coming_soon': 'Your coach will create a plan for you soon',
    'instructions': 'Instructions',
    
    // Messaging
    'messages': 'Messages',
    'sessions': 'Sessions',
    'coach_messaging': 'Coach Messaging',
    'coach_messaging_subtitle': 'Message your coach and book sessions',
    'book_video_call': 'Book Video Call',
    'book_video_call_hint': 'Schedule a video session with your coach',
    'start_conversation_with_coach': 'Start a conversation with your coach',
    'ask_questions_about_workouts_nutrition': 'Ask about workouts or nutrition',
    'type_a_message': 'Type a message...',
    'photo': 'Photo',
    'video': 'Video',
    'file': 'File',
    'request': 'Request',
    'request_video_call': 'Request Video Call',
    'do_you_want_video_call_with_coach': 'Do you want to request a video call with your coach?',
    'video_call_request_message': 'Video call request',
    'video_call_request_sent': 'Video call request sent',
    'type_message': 'Type a message...',
    'send': 'Send',
    'quota_warning': '{remaining} messages remaining this month',
    'quota_exceeded': 'Message quota exceeded',
    
    // Store
    'categories': 'Categories',
    'featured': 'Featured Products',
    'store_all': 'All',
    'store_supplements': 'Supplements',
    'store_equipment': 'Equipment',
    'store_apparel': 'Apparel',
    'store_accessories': 'Accessories',
    'store_title': 'FitCoach Store',
    'store_subtitle': 'Supplements and gear picked for you',
    'store_search_placeholder': 'Search products or brands',
    'store_products': 'Products',
    'store_cart': 'Cart',
    'store_orders': 'Orders',
    'store_popular': 'Popular',
    'store_no_products': 'No products in this category',
    'store_no_orders': 'No orders yet',
    'store_added_to_cart': 'Added to cart',
    'store_status_processing': 'Processing',
    'store_status_shipped': 'Shipped',
    'store_status_delivered': 'Delivered',
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',
    'out_of_stock': 'Out of Stock',
    'currency_sar': 'SAR',
    'reviews_count': '({count} reviews)',
    'cart_empty': 'Cart is empty',
    'shopping_cart': 'Shopping Cart',
    'total': 'Total:',
    'checkout': 'Checkout',
    'checkout_message': 'You will be redirected to payment',
    'ok': 'OK',
    'description': 'Description',
    
    // Account
    'profile': 'Profile',
    'subscription': 'Subscription',
    'settings': 'Settings',
    'logout': 'Logout',
    'tagline': 'Your Fitness Journey Starts Here',
    'welcome_back': 'Welcome Back',
    'sign_in_subtitle': 'Sign in to your account',
    'email_or_phone': 'Email or Phone',
    'email': 'Email',
    'email_or_phone_hint': 'example@email.com or +966...',
    'password': 'Password',
    'password_hint': 'Enter your password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot Password?',
    'or': 'OR',
    'continue_with_phone': 'Continue with Phone',
    'or_continue_with': 'Or continue with',
    'dont_have_account': 'Don\'t have an account?',
    'sign_up': 'Sign Up',
    'otp_invalid_phone': 'Please enter a valid Saudi phone number',
    'otp_incomplete': 'Please enter the complete OTP code',
    'change_phone': 'Change phone number',
    'onboarding_slide1_title': 'Welcome to FitCoach+',
    'onboarding_slide1_desc': 'Your fitness journey starts here with professional coaches',
    'onboarding_slide2_title': 'Personalized Workout Plans',
    'onboarding_slide2_desc': 'Get workout plans tailored to your goals and condition',
    'onboarding_slide3_title': 'Connect with Your Coach',
    'onboarding_slide3_desc': 'Direct communication with your coach for guidance and support',
    'onboarding_coaching_title': 'Your Personal Coach Awaits',
    'onboarding_coaching_desc': 'Connect with certified fitness professionals who understand your goals. Get real-time guidance, motivation, and accountability through personalized coaching.',
    'onboarding_nutrition_title': 'Fuel Your Transformation',
    'onboarding_nutrition_desc': 'Discover customized meal plans designed for your body and goals. Track macros effortlessly and learn sustainable nutrition habits that last a lifetime.',
    'onboarding_workouts_title': 'Train Smarter, Not Harder',
    'onboarding_workouts_desc': 'Access scientifically-designed workout programs that adapt to your fitness level. Every exercise is demonstrated with proper form to maximize results and prevent injury.',
    'onboarding_store_title': 'Everything You Need, One Place',
    'onboarding_store_desc': 'Shop premium supplements, training gear, and wellness products curated by fitness experts. Quality nutrition and equipment to support your journey.',
    'onboarding_go_to_slide': 'Go to slide {index}',
    'get_started': 'Get Started',
    'sign_in': 'Sign In',
    'signing_in': 'Signing in...',
    'forgot_password_title': 'Forgot Password',
    'forgot_password_desc': 'Enter your email and we\'ll send you a reset link',
    'reset_link_sent': 'Reset link sent to your email',
    'other': 'Other',
    'workout_frequency': 'Days per week',
    'intake_first_title': 'Quick start intake',
    'intake_first_subtitle': 'Just three quick steps to get started',
    'intake_first_complete': 'Complete intake',
    'intake_first_gender_title': 'Select your gender',
    'intake_first_gender_desc': 'Help us tailor your experience',
    'intake_first_goal_title': 'What\'s your main goal?',
    'intake_first_goal_desc': 'Choose the focus of your plan',
    'intake_first_fat_loss_desc': 'Burn fat and feel lighter',
    'intake_first_muscle_gain_desc': 'Build strength and size',
    'intake_first_fitness_desc': 'Improve overall health',
    'intake_first_location_title': 'Where do you work out?',
    'intake_first_location_desc': 'We tailor your workouts to your space',
    'intake_first_gym_desc': 'Access full gym equipment',
    'intake_first_home_desc': 'Train with minimal equipment',
    'intake_second_title': 'Advanced intake',
    'intake_second_subtitle': 'Tell us more for a personalized plan',
    'intake_second_complete': 'Complete intake',
  };
  
  // Arabic translations

static const Map<String, String> _arabicTranslations = {
    'auth_app_name': 'فيت كوتش',
    'auth_tagline': 'رحلتك الرياضية تبدأ هنا',
    'auth_welcome': 'مرحباً',
    'auth_welcome_subtitle': 'سجل الدخول للمتابعة',
    'auth_continue_with_email': 'المتابعة بالبريد الإلكتروني',
    'auth_continue_with_phone': 'المتابعة برقم الهاتف',
    'auth_email_or_phone': 'البريد الإلكتروني أو رقم الهاتف',
    'auth_email_or_phone_placeholder': 'name@example.com أو +966...',
    'auth_or_divider': 'أو',
    'auth_phone_will_receive_otp': 'سنرسل رمز التحقق إلى هذا الرقم',
    'auth_enter_otp': 'أدخل رمز التحقق',
    'auth_otp_sent': 'تم إرسال رمز إلى',
    'auth_sign_in': 'تسجيل الدخول',
    'auth_sign_up': 'إنشاء حساب',
    'auth_back': 'رجوع',
    'auth_no_account': 'ليس لديك حساب؟',
    'auth_have_account': 'لديك حساب بالفعل؟',
    'auth_create_account': 'إنشاء حساب',
    'auth_create_account_subtitle': 'انضم إلى فيت كوتش وابدأ رحلتك',
    'auth_full_name': 'الاسم الكامل',
    'auth_email': 'البريد الإلكتروني',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': 'كلمة المرور',
    'auth_password_placeholder': 'أدخل كلمة المرور',
    'auth_forgot_password': 'نسيت كلمة المرور؟',
    'auth_forgot_password_title': 'نسيت كلمة المرور',
    'auth_forgot_password_desc': 'أدخل البريد الإلكتروني أو رقم الهاتف لإرسال رابط إعادة التعيين',
    'auth_reset_link_sent': 'تم إرسال رابط إعادة التعيين',
    'auth_send': 'إرسال',
    'auth_cancel': 'إلغاء',
    'auth_confirm_password': 'تأكيد كلمة المرور',
    'auth_confirm_password_placeholder': 'أعد إدخال كلمة المرور',
    'auth_missing_fields': 'يرجى تعبئة جميع الحقول المطلوبة',
    'auth_password_mismatch': 'كلمتا المرور غير متطابقتين',
    'auth_try_demo': 'تجربة العرض',
    'auth_demo_unavailable': 'وضع العرض متاح فقط عند البناء مع DEMO_MODE',
    'auth_demo_credentials': 'بيانات الدخول التجريبية',
    'auth_demo_user': 'مستخدم تجريبي',
    'auth_demo_coach': 'مدرب تجريبي',
    'auth_demo_admin': 'مدير تجريبي',
    'auth_phone': 'رقم الهاتف',
    'auth_phone_placeholder': '+966 5X XXX XXXX',
    'auth_verify': 'تحقق',
    'auth_resend': 'إعادة الإرسال',
    'auth_resend_in': 'إعادة الإرسال خلال',
    'auth_attempts_remaining': 'محاولات متبقية',
    'auth_change_phone': 'تغيير رقم الهاتف',
    'splash_headline_en': 'Your Fitness Journey Starts Now',
    'splash_headline_ar': 'رحلتك الرياضية تبدأ الآن',
    'splash_start': 'Start / ابدأ',
    'account': 'الحساب',
    'additional_info': 'معلومات إضافية',
    'app_name': 'عاش',
    'appointment_details': 'تفاصيل الموعد',
    'ask_questions_about_workouts_nutrition': 'اسأل عن التمارين أو التغذية',
    'assessment': 'تقييم',
    'back': 'رجوع',
    'calories': 'السعرات',
    'can_join_now': 'يمكنك الانضمام الآن',
    'cancel': 'إلغاء',
    'cannot_join_call': 'لا يمكن الانضمام للمكالمة',
    'cannot_join_yet': 'لا يمكنك الانضمام بعد',
    'change_phone': 'تغيير رقم الهاتف',
    'chat': 'محادثة',
    'chest_day': 'يوم الصدر',
    'coach': 'المدرب',
    'coach_messaging': 'مراسلة المدرب',
    'messages': 'الرسائل',
    'sessions': 'الجلسات',
    'coach_messaging_subtitle': 'تواصل مع مدربك واحجز جلسات',
    'book_video_call': 'حجز مكالمة فيديو',
    'book_video_call_hint': 'جدول جلسة فيديو مع مدربك',
    'completed': 'مكتمل',
    'connect_with_coach': 'تواصل مع مدربك',
    'continue': 'متابعة',
    'continue_with_phone': 'متابعة عبر الهاتف',
    'current_plan': 'الخطة الحالية',
    'date_time': 'التاريخ والوقت',
    'day_streak': 'سلسلة الأيام',
    'do_you_want_video_call_with_coach': 'هل تريد إجراء مكالمة فيديو مع المدرب؟',
    'dont_have_account': 'ليس لديك حساب؟',
    'duration': 'المدة',
    'email': 'البريد الإلكتروني',
    'email_or_phone': 'البريد الإلكتروني أو الهاتف',
    'email_or_phone_hint': 'example@email.com أو +966...',
    'enter_otp': 'أدخل رمز التحقق',
    'enter_phone': 'أدخل رقم هاتفك',
    'exercises': 'تمارين',
    'no_active_workout_plan': 'لا توجد خطة تمرين نشطة',
    'workout_plan_coming_soon': 'سيقوم مدربك بإنشاء خطة لك قريباً',
    'workout_select_day': 'اختر يوماً لعرض التمارين',
    'workout_overview': 'نظرة عامة على التمرين',
    'workout_day': 'يوم {number}',
    'workout_progress': '{completed} من {total} تمارين مكتملة',
    'fat_loss': 'فقدان الدهون',
    'female': 'أنثى',
    'file': 'ملف',
    'forgot_password': 'نسيت كلمة المرور؟',
    'forgot_password_desc': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين',
    'forgot_password_title': 'نسيت كلمة المرور',
    'gender': 'الجنس',
    'general_fitness': 'لياقة عامة',
    'get_started': 'ابدأ الآن',
    'goal': 'ما هدفك الرئيسي؟',
    'gym': 'النادي الرياضي',
    'home': 'الرئيسية',
    'home_auto_updated': 'محدث تلقائياً',
    'home_calories_burned': 'سعرات محروقة',
    'home_calories_consumed': 'سعرات مستهلكة',
    'home_coach': 'المدرب',
    'home_coach_desc': 'محادثة ومكالمات فيديو',
    'home_fitness_score': 'مؤشر اللياقة',
    'home_hello': 'مرحباً',
    'home_locked': 'مقفل',
    'home_nutrition': 'التغذية',
    'home_nutrition_desc': 'الوجبات والماكروز والأهداف اليومية',
    'home_quick_access': 'وصول سريع',
    'home_ready': 'هل أنت مستعد للجلسة التالية؟',
    'home_store': 'المتجر',
    'home_store_desc': 'مكملات ومعدات',
    'home_updated_by_coach': 'محدث بواسطة المدرب',
    'home_workouts': 'التمارين',
    'home_workouts_completed': 'تمارين مكتملة',
    'home_workouts_desc': 'خطط التدريب وتمرين اليوم',
    'join_video_call': 'انضم لمكالمة الفيديو',
    'lets_know_you': 'دعنا نتعرف عليك',
    'location': 'أين تفضل التمرين؟',
    'male': 'ذكر',
    'meals': 'وجبات',
    'message_coach': 'راسل المدرب',
    'minute_short': 'د',
    'minutes': 'دقائق',
    'monthly_quota': 'الحصة الشهرية',
    'muscle_gain': 'بناء العضلات',
    'next': 'التالي',
    'notes': 'ملاحظات',
    'nutrition': 'التغذية',
    'sets': 'مجموعات',
    'reps': 'تكرارات',
    'substitute': 'بديل',
    'substitute_exercise': 'استبدال التمرين',
    'no_alternatives_available': 'لا توجد بدائل متاحة',
    'exercise_substituted_successfully': 'تم استبدال التمرين بنجاح',
    'workout_injury_conflict': 'قد يتعارض هذا التمرين مع إصابتك',
    'onboarding_coaching_desc': 'تواصل مع متخصصي اللياقة البدنية المعتمدين الذين يفهمون أهدافك. احصل على إرشادات فورية، تحفيز، ومتابعة من خلال التدريب الشخصي.',
    'onboarding_coaching_title': 'مدربك الشخصي في انتظارك',
    'onboarding_go_to_slide': 'الانتقال إلى الشريحة {index}',
    'onboarding_nutrition_desc': 'اكتشف خطط وجبات مخصصة مصممة لجسمك وأهدافك. تتبع العناصر الغذائية بسهولة وتعلم عادات تغذية مستدامة تدوم مدى الحياة.',
    'onboarding_nutrition_title': 'غذِّ تحولك',
    'onboarding_store_desc': 'تسوق المكملات الفاخرة، معدات التدريب، ومنتجات العافية المختارة من قبل خبراء اللياقة. تغذية ومعدات عالية الجودة لدعم رحلتك.',
    'onboarding_store_title': 'كل ما تحتاجه، في مكان واحد',
    'onboarding_workouts_desc': 'احصل على برامج تمارين مصممة علمياً تتكيف مع مستوى لياقتك. كل تمرين معروض مع الأداء الصحيح لتعظيم النتائج ومنع الإصابات.',
    'onboarding_workouts_title': 'تدرب بذكاء، وليس بجهد أكبر',
    'or': 'أو',
    'or_continue_with': 'أو المتابعة عبر',
    'otp_incomplete': 'يرجى إدخال رمز التحقق كاملاً',
    'otp_invalid_phone': 'يرجى إدخال رقم سعودي صحيح',
    'password': 'كلمة المرور',
    'password_hint': 'أدخل كلمة المرور',
    'phone_hint': '+966 5X XXX XXXX',
    'trial_period': 'فترة التجربة',
    'trial_expiring': 'لديك {days} أيام متبقية من الوصول المجاني',
    'trial_expired': 'انتهت فترة التجربة',
    'upgrade_to_premium': 'ترقية إلى Premium',
    'upgrade_prompt': 'قم بالترقية إلى Premium للوصول غير المحدود إلى خطط التغذية',
    'protein': 'بروتين',
    'carbs': 'كربوهيدرات',
    'fats': 'دهون',
    'consumed': 'مستهلك',
    'remaining': 'متبقي',
    'cal_unit': 'سعرة',
    'more_items': '+ {count} أكثر',
    'todays_meals': 'وجبات اليوم',
    'no_active_nutrition_plan': 'لا توجد خطة تغذية نشطة',
    'nutrition_plan_coming_soon': 'سيقوم مدربك بإنشاء خطة لك قريباً',
    'instructions': 'التعليمات',
    'photo': 'صورة',
    'progress': 'التقدم',
    'quick_actions': 'إجراءات سريعة',
    'remember_me': 'تذكرني',
    'request': 'طلب',
    'request_video_call': 'طلب مكالمة فيديو',
    'resend': 'إعادة إرسال',
    'reset_link_sent': 'تم إرسال رابط إعادة التعيين إلى بريدك',
    'send': 'إرسال',
    'send_otp': 'إرسال رمز التحقق',
    'shop_products': 'تسوق المنتجات',
    'store_all': 'الكل',
    'store_supplements': 'مكملات',
    'store_equipment': 'معدات',
    'store_apparel': 'ملابس',
    'store_accessories': 'إكسسوارات',
    'store_title': 'متجر فت كوتش',
    'store_subtitle': 'مكملات ومعدات مختارة لك',
    'store_search_placeholder': 'ابحث عن منتج أو علامة تجارية',
    'store_products': 'المنتجات',
    'store_cart': 'السلة',
    'store_orders': 'الطلبات',
    'store_popular': 'الأكثر طلباً',
    'store_no_products': 'لا توجد منتجات في هذه الفئة',
    'store_no_orders': 'لا توجد طلبات بعد',
    'store_added_to_cart': 'تمت الإضافة إلى السلة',
    'store_status_processing': 'قيد المعالجة',
    'store_status_shipped': 'تم الشحن',
    'store_status_delivered': 'تم التوصيل',
    'out_of_stock': 'نفذ المخزون',
    'currency_sar': 'ر.س',
    'reviews_count': '({count} تقييم)',
    'cart_empty': 'السلة فارغة',
    'shopping_cart': 'سلة التسوق',
    'total': 'الإجمالي:',
    'checkout': 'إتمام الطلب',
    'checkout_message': 'سيتم تحويلك إلى الدفع',
    'ok': 'حسناً',
    'description': 'الوصف',
    'sign_in': 'تسجيل الدخول',
    'sign_in_subtitle': 'سجل الدخول إلى حسابك',
    'sign_up': 'إنشاء حساب',
    'signing_in': 'جارٍ تسجيل الدخول...',
    'skip': 'تخطي',
    'start_conversation_with_coach': 'ابدأ محادثة مع المدرب',
    'store': 'المتجر',
    'tagline': 'رحلتك الرياضية تبدأ هنا',
    'todays_nutrition': 'تغذية اليوم',
    'todays_workout': 'تمرين اليوم',
    'type': 'النوع',
    'type_a_message': 'اكتب رسالة...',
    'unknown': 'غير معروف',
    'upgrade': 'ترقية',
    'user': 'مستخدم',
    'verify': 'تحقق',
    'video': 'فيديو',
    'video_call': 'مكالمة فيديو',
    'video_call_request_message': 'طلب مكالمة فيديو',
    'video_call_request_sent': 'تم إرسال طلب مكالمة الفيديو',
    'view_achievements': 'عرض الإنجازات',
    'welcome': 'مرحباً بك في عاش',
    'welcome_back': 'مرحباً بعودتك',
    'workout': 'التمارين',
    'workouts': 'التمارين',
    'your_progress': 'تقدمك',
    'other': '\u0622\u062e\u0631',
    'workout_frequency': '\u0639\u062f\u062f \u0627\u0644\u0623\u064a\u0627\u0645 \u0628\u0627\u0644\u0623\u0633\u0628\u0648\u0639',
    'intake_first_title': '\u0627\u0644\u0623\u0633\u0626\u0644\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629',
    'intake_first_subtitle': '\u062b\u0644\u0627\u062b \u062e\u0637\u0648\u0627\u062a \u0633\u0631\u064a\u0639\u0629 \u0644\u0644\u0628\u062f\u0621',
    'intake_first_complete': '\u0625\u0643\u0645\u0627\u0644 \u0627\u0644\u0627\u0633\u062a\u0628\u064a\u0627\u0646',
    'intake_first_gender_title': '\u0627\u062e\u062a\u0631 \u0627\u0644\u062c\u0646\u0633',
    'intake_first_gender_desc': '\u0644\u0645\u0633\u0627\u0639\u062f\u062a\u0646\u0627 \u0639\u0644\u0649 \u062a\u062e\u0635\u064a\u0635 \u0627\u0644\u062a\u062c\u0631\u0628\u0629',
    'intake_first_goal_title': '\u0645\u0627 \u0647\u0648 \u0647\u062f\u0641\u0643 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u061f',
    'intake_first_goal_desc': '\u0627\u062e\u062a\u0631 \u062a\u0631\u0643\u064a\u0632 \u062e\u0637\u062a\u0643',
    'intake_first_fat_loss_desc': '\u062d\u0631\u0642 \u0627\u0644\u062f\u0647\u0648\u0646 \u0648\u0627\u0644\u0634\u0639\u0648\u0631 \u0628\u062e\u0641\u0629',
    'intake_first_muscle_gain_desc': '\u0628\u0646\u0627\u0621 \u0627\u0644\u0642\u0648\u0629 \u0648\u0627\u0644\u0639\u0636\u0644\u0627\u062a',
    'intake_first_fitness_desc': '\u062a\u062d\u0633\u064a\u0646 \u0627\u0644\u0635\u062d\u0629 \u0627\u0644\u0639\u0627\u0645\u0629',
    'intake_first_location_title': '\u0623\u064a\u0646 \u062a\u062a\u0645\u0631\u0646\u061f',
    'intake_first_location_desc': '\u0646\u062e\u0635\u0635 \u0627\u0644\u062a\u0645\u0631\u064a\u0646 \u062d\u0633\u0628 \u0645\u0643\u0627\u0646\u0643',
    'intake_first_gym_desc': '\u062a\u0648\u0641\u0631 \u0643\u0627\u0645\u0644 \u0645\u0639\u062f\u0627\u062a \u0627\u0644\u062c\u064a\u0645',
    'intake_first_home_desc': '\u062a\u0645\u0631\u064a\u0646 \u0628\u0645\u0639\u062f\u0627\u062a \u0628\u0633\u064a\u0637\u0629',
    'intake_second_title': '\u0627\u0644\u0623\u0633\u0626\u0644\u0629 \u0627\u0644\u0645\u062a\u0642\u062f\u0645\u0629',
    'intake_second_subtitle': '\u0623\u062e\u0628\u0631\u0646\u0627 \u0627\u0644\u0645\u0632\u064a\u062f \u0644\u062e\u0637\u0629 \u0645\u062e\u0635\u0635\u0629',
    'intake_second_complete': '\u0625\u0643\u0645\u0627\u0644 \u0627\u0644\u0627\u0633\u062a\u0628\u064a\u0627\u0646',
    'home_location': '\u0627\u0644\u0645\u0646\u0632\u0644',
    'age': '\u0627\u0644\u0639\u0645\u0631',
    'years': '\u0633\u0646\u0629',
    'weight': '\u0627\u0644\u0648\u0632\u0646',
    'height': '\u0627\u0644\u0637\u0648\u0644',
    'kg': '\u0643\u062c\u0645',
    'cm': '\u0633\u0645',
    'complete': '\u0625\u0643\u0645\u0627\u0644',
    'intake_incomplete': '\u064a\u0631\u062c\u0649 \u0625\u0643\u0645\u0627\u0644 \u062c\u0645\u064a\u0639 \u0627\u0644\u062d\u0642\u0648\u0644 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629',
    'intake_select_option': '\u064a\u0631\u062c\u0649 \u0627\u062e\u062a\u064a\u0627\u0631 \u062e\u064a\u0627\u0631',
    'experience_level_title': '\u0645\u0627 \u0647\u0648 \u0645\u0633\u062a\u0648\u0649 \u062e\u0628\u0631\u062a\u0643\u061f',
    'experience_level_desc': '\u064a\u0633\u0627\u0639\u062f\u0646\u0627 \u0647\u0630\u0627 \u0639\u0644\u0649 \u062a\u062e\u0635\u064a\u0635 \u062e\u0637\u0629 \u0627\u0644\u062a\u062f\u0631\u064a\u0628',
    'experience_beginner': '\u0645\u0628\u062a\u062f\u0626',
    'experience_beginner_desc': '0-6 \u0623\u0634\u0647\u0631',
    'experience_intermediate': '\u0645\u062a\u0648\u0633\u0637',
    'experience_intermediate_desc': '6-24 \u0634\u0647\u0631\u0627\u064b',
    'experience_advanced': '\u0645\u062a\u0642\u062f\u0645',
    'experience_advanced_desc': '\u0623\u0643\u062b\u0631 \u0645\u0646 \u0633\u0646\u062a\u064a\u0646',
    'intake_second_age_title': '\u0645\u0627 \u0647\u0648 \u0639\u0645\u0631\u0643\u061f',
    'intake_second_age_desc': '\u0646\u0633\u062a\u062e\u062f\u0645 \u0647\u0630\u0627 \u0644\u062a\u062e\u0635\u064a\u0635 \u062e\u0637\u062a\u0643',
    'intake_second_body_metrics_title': '\u0627\u0644\u0645\u0642\u0627\u064a\u064a\u0633 \u0627\u0644\u062c\u0633\u0645\u064a\u0629',
    'intake_second_body_metrics_desc': '\u0623\u062f\u062e\u0644 \u0648\u0632\u0646\u0643 \u0648\u0637\u0648\u0644\u0643 \u0627\u0644\u062d\u0627\u0644\u064a\u064a\u0646',
    'intake_second_frequency_title': '\u0639\u062f\u062f \u0645\u0631\u0627\u062a \u0627\u0644\u062a\u0645\u0631\u064a\u0646',
    'intake_second_frequency_desc': '\u0643\u0645 \u064a\u0648\u0645\u0627\u064b \u064a\u0645\u0643\u0646\u0643 \u0627\u0644\u062a\u0645\u0631\u064a\u0646 \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639\u061f',
    'intake_second_injuries_title': '\u0647\u0644 \u0644\u062f\u064a\u0643 \u0623\u064a \u0625\u0635\u0627\u0628\u0627\u062a\u061f',
    'intake_second_injuries_desc': '\u0633\u0646\u0639\u062f\u0644 \u0627\u0644\u062e\u0637\u0629 \u0644\u0644\u062d\u0641\u0627\u0638 \u0639\u0644\u0649 \u0633\u0644\u0627\u0645\u062a\u0643',
    'intake_second_injuries_none': '\u0644\u0627 \u062a\u0648\u062c\u062f \u0625\u0635\u0627\u0628\u0627\u062a\u061f \u0631\u0627\u0626\u0639\u0021 \u0623\u0643\u0645\u0644',
    'injury_shoulder': '\u0627\u0644\u0643\u062a\u0641',
    'injury_knee': '\u0627\u0644\u0631\u0643\u0628\u0629',
    'injury_lower_back': '\u0623\u0633\u0641\u0644 \u0627\u0644\u0638\u0647\u0631',
    'injury_neck': '\u0627\u0644\u0631\u0642\u0628\u0629',
    'injury_ankle': '\u0627\u0644\u0643\u0627\u062d\u0644',
    'intake_prompt_title': '\u0623\u0643\u0645\u0644 \u0627\u0633\u062a\u0628\u064a\u0627\u0646 \u0627\u0644\u062a\u0645\u0631\u064a\u0646',
    'intake_prompt_description': '\u0623\u0643\u0645\u0644 \u0628\u0639\u0636 \u0627\u0644\u0623\u0633\u0626\u0644\u0629 \u0644\u0641\u062a\u062d \u062e\u0637\u0629 \u0645\u062e\u0635\u0635\u0629 \u0623\u0648 \u0627\u062d\u062c\u0632 \u0645\u0643\u0627\u0644\u0645\u0629 \u0645\u062c\u0627\u0646\u064a\u0629 \u0645\u0639 \u0627\u0644\u0645\u062f\u0631\u0628\u002e',
    'intake_prompt_option1_title': '\u062e\u0637\u0629 \u062a\u0645\u0631\u064a\u0646 \u0645\u062e\u0635\u0635\u0629',
    'intake_prompt_option1_desc': '\u0623\u062c\u0628 \u0639\u0646 \u0623\u0633\u0626\u0644\u0629 \u0642\u0635\u064a\u0631\u0629 \u0644\u062a\u062e\u0635\u064a\u0635 \u062a\u062f\u0631\u064a\u0628\u0643\u002e',
    'intake_prompt_option2_title': '\u0645\u0643\u0627\u0644\u0645\u0629 \u0641\u064a\u062f\u064a\u0648 \u0645\u062c\u0627\u0646\u064a\u0629 \u0645\u0639 \u0627\u0644\u0645\u062f\u0631\u0628',
    'intake_prompt_option2_desc': '\u0627\u062d\u0635\u0644 \u0639\u0644\u0649 \u0625\u0631\u0634\u0627\u062f \u0648\u0645\u062a\u0627\u0628\u0639\u0629 \u0645\u0646 \u0645\u062f\u0631\u0628\u002e',
    'intake_prompt_free_call': '\u0645\u062c\u0627\u0646\u064b\u0627 \u0644\u0643',
    'intake_prompt_book_call': '\u0627\u062d\u062c\u0632 \u0645\u0643\u0627\u0644\u0645\u0629',
    'intake_prompt_complete': '\u0623\u0643\u0645\u0644 \u0627\u0644\u0627\u0633\u062a\u0628\u064a\u0627\u0646',
    'intake_prompt_later': '\u0644\u0627\u062d\u0642\u0627',
    'intake_generating_title': '\u062c\u0627\u0631\u064d \u0625\u0646\u0634\u0627\u0621 \u062e\u0637\u062a\u0643',
    'intake_generating_desc': '\u0646\u0642\u0648\u0645 \u0627\u0644\u0622\u0646 \u0628\u0625\u0646\u0634\u0627\u0621 \u062e\u0637\u0629 \u062a\u0645\u0631\u064a\u0646 \u0645\u062e\u0635\u0635\u0629 \u0644\u0643\u002e',
  };
}
