name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Backend install & lint
        run: |
          cd backend
          npm ci
          npm run lint
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Mobile build
        run: |
          cd mobile
          flutter pub get
          flutter analyze
